name       : python3-qt5
version    : 5.7.1
release    : 9
source     :
    - https://superb-sea2.dl.sourceforge.net/project/pyqt/PyQt5/PyQt-5.7.1/PyQt5_gpl-5.7.1.tar.gz : be849f212a074049b9ebc10b6c07dddefb86e6d30e8df8a5c715cbb2cf7fad14
license    : GPL-3.0
component  : programming.python
summary    : python3-qt5 are the python3 bindings for Qt5.
description: |
    python3-qt5 are the python3 bindings for Qt5.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(python-3.5)
    - pkgconfig(Qt5Bluetooth)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Location)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - python3-dbus
    - python3-sip-devel
rundeps    :
    - python3-sip
    - python-qt5
setup      : |
    python3 configure.py --confirm-license --no-sip-files -q /usr/bin/qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
    rm -rf $installdir/usr/bin
    rm -rf $installdir/usr/lib64
    rm -rf $installdir/usr/share
