name       : python3-qt5
version    : 4.11.4
release    : 1
source     :
    - http://downloads.sourceforge.net/project/pyqt/PyQt4/PyQt-4.11.4/PyQt-x11-gpl-4.11.4.tar.gz : fc1fe77495432ba3b0d74ff5cb164d375a97f5dddb728256330f615a7cdcf407
license    : GPL-3.0
summary    : python3-qt5 are the python3 bindings for Qt5.
description: |
    python3-qt5 are the python3 bindings for Qt5.
builddeps  :
    - pkgconfig(python-3.4)
    - pkgconfig(Qt5Core)
    - python3-dbus
    - python3-sip-devel
setup      : |
    python3 configure-ng.py --confirm-license --no-sip-files --qsci-api -q /usr/bin/qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
