name       : python3-qt5
version    : 5.10.1
release    : 22
source     :
    - https://jaist.dl.sourceforge.net/project/pyqt/PyQt5/PyQt-5.10.1/PyQt5_gpl-5.10.1.tar.gz : 9932e971e825ece4ea08f84ad95017837fa8f3f29c6b0496985fa1093661e9ef
license    : GPL-3.0
component  : programming.python
summary    : python3-qt5 are the python3 bindings for Qt5
description: |
    python3-qt5 are the python3 bindings for Qt5.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(python3)
    - pkgconfig(Qt5Bluetooth)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - python3-dbus
    - python3-sip-devel
rundeps    :
    - python3-sip
    - python-qt5
setup      : |
    %apply_patches

    python3 configure.py --confirm-license \
        --no-sip-files \
        -q /usr/bin/qmake \
        QMAKE_CFLAGS_RELEASE="$CFLAGS" \
        QMAKE_CXXFLAGS_RELEASE="$CXXFLAGS" \
        QMAKE_LFLAGS_RELEASE="$LDFLAGS"
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
    rm -f $installdir/usr/bin/{pylupdate5,pyrcc5}
    rm -rf $installdir/usr/lib64
