name       : python3-qt5
version    : 5.15.2
release    : 40
source     :
    - https://pypi.python.org/packages/source/P/PyQt5/PyQt5-5.15.2.tar.gz : 372b08dc9321d1201e4690182697c5e7ffb2e0770e6b4a45519025134b12e4fc
homepage   : https://riverbankcomputing.com/software/pyqt/intro
license    : GPL-3.0-or-later
component  : programming.python
summary    : python3-qt5 are the python3 bindings for Qt5
description: |
    python3-qt5 are the python3 bindings for Qt5.
replaces   :
    - python-qt5
builddeps  :
    - pkgconfig(Qt5Bluetooth)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Location)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(x11)
    - pkgconfig(dbus-python)
    - pkgconfig(python3)
    - python-sip
rundeps    :
    - python-sip
setup      : |
    python3 configure.py --confirm-license \
        -q /usr/bin/qmake \
        QMAKE_CFLAGS_RELEASE="$CFLAGS" \
        QMAKE_CXXFLAGS_RELEASE="$CXXFLAGS" \
        QMAKE_LFLAGS_RELEASE="$LDFLAGS"
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir" -j1
