name       : python3-qt5
version    : 5.13.1
release    : 32
source     :
    - https://www.riverbankcomputing.com/static/Downloads/PyQt5/5.13.1/PyQt5_gpl-5.13.1.tar.gz : 54b7f456341b89eeb3930e786837762ea67f235e886512496c4152ebe106d4af
license    : GPL-3.0-or-later
component  : programming.python
summary    : python3-qt5 are the python3 bindings for Qt5
description: |
    python3-qt5 are the python3 bindings for Qt5.
builddeps  :
    - pkgconfig(Qt5Bluetooth)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Location)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(dbus-python)
    - pkgconfig(python3)
    - python3-dbus
    - python3-sip-devel
    - python-enum34
rundeps    :
    - python3-sip
    - python-qt5
    - python-enum34
setup      : |
    python3 configure.py --confirm-license \
        --no-sip-files \
        -q /usr/bin/qmake \
        QMAKE_CFLAGS_RELEASE="$CFLAGS" \
        QMAKE_CXXFLAGS_RELEASE="$CXXFLAGS" \
        QMAKE_LFLAGS_RELEASE="$LDFLAGS"
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir" -j1
    rm -f $installdir/usr/bin/{pylupdate5,pyrcc5}
    rm -rf $installdir/usr/lib64
