name       : python3-qt5
version    : 5.15.6
release    : 44
source     :
    - https://pypi.python.org/packages/source/P/PyQt5/PyQt5-5.15.6.tar.gz : 80343bcab95ffba619f2ed2467fd828ffeb0a251ad7225be5fc06dcc333af452
homepage   : https://riverbankcomputing.com/software/pyqt/intro
license    : GPL-3.0-or-later
component  : programming.python
summary    : python3-qt5 are the python3 bindings for Qt5
description: |
    python3-qt5 are the python3 bindings for Qt5.
replaces   :
    - python-qt5
builddeps  :
    - pkgconfig(Qt5Bluetooth)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Location)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(x11)
    - pkgconfig(dbus-python)
    - pkgconfig(python3)
    - pyqt-builder
    - python-pyqt5-sip
    - python-sip
rundeps    :
    - python-pyqt5-sip
setup      : |
    sip-build \
        --confirm-license \
        --no-make \
        --api-dir /usr/share/qt5/qsci/api/python
build      : |
    %make -C build
install    : |
    %make_install -C build INSTALL_ROOT="$installdir"
