name       : python3-qt5
version    : 5.5
release    : 3
source     :
    - http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.5/PyQt-gpl-5.5.tar.gz : cdd1bb55b431acdb50e9210af135428a13fb32d7b1ab86e972ac7101f6acd814
license    : GPL-3.0
summary    : python3-qt5 are the python3 bindings for Qt5.
description: |
    python3-qt5 are the python3 bindings for Qt5.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(python-3.4)
    - pkgconfig(Qt5Gui)
    - python3-dbus
    - python3-sip-devel
rundeps :
    - python3-sip
    - python-qt5
setup      : |
    python3 configure.py --confirm-license --no-sip-files -q /usr/bin/qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
    rm -rf $installdir/usr/bin
    rm -rf $installdir/usr/lib64
    rm -rf $installdir/usr/share
    # Remove duplicate designer and PyQt5 qml plugins
    rm -rf $installdir/usr/lib/qt5
