name       : python3-qt5
version    : 5.14.2
release    : 35
source     :
    - https://pypi.python.org/packages/source/P/PyQt5/PyQt5-5.14.2.tar.gz : bd230c6fd699eabf1ceb51e13a8b79b74c00a80272c622427b80141a22269eb0
license    : GPL-3.0-or-later
component  : programming.python
summary    : python3-qt5 are the python3 bindings for Qt5
description: |
    python3-qt5 are the python3 bindings for Qt5.
builddeps  :
    - pkgconfig(Qt5Bluetooth)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Location)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(x11)
    - pkgconfig(dbus-python)
    - pkgconfig(python3)
    - python3-dbus
    - python3-sip-devel
    - python-enum34
rundeps    :
    - python3-sip
    - python-qt5
    - python-enum34
setup      : |
    %patch -p1 < $pkgfiles/update-timeline.patch
    python3 configure.py --confirm-license \
        --no-sip-files \
        -q /usr/bin/qmake \
        QMAKE_CFLAGS_RELEASE="$CFLAGS" \
        QMAKE_CXXFLAGS_RELEASE="$CXXFLAGS" \
        QMAKE_LFLAGS_RELEASE="$LDFLAGS"
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir" -j1
    rm -f $installdir/usr/bin/{pylupdate5,pyrcc5}
    rm -rf $installdir/usr/lib64
